image: node:20

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci

build_frontend:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
